const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function fixture(){
 const memory=new Map();const element={innerHTML:'',querySelectorAll:()=>[]};let time=1000;
 const context={console,crypto:globalThis.crypto,performance:{now:()=>time},setTimeout,clearTimeout,alert:()=>{},confirm:()=>true,URL,Blob,location:{hash:'#/learn',pathname:'/',origin:'http://localhost'},history:{pushState:()=>{}},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)},document:{getElementById:id=>id==='app'?element:null},window:{addEventListener:()=>{},supabase:{createClient:()=>({})}}};
 vm.createContext(context);
 const html=fs.readFileSync('index.html','utf8');for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))vm.runInContext(m[1],context);
 for(const file of ['scoring.js','sentences.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context);
 vm.runInContext(fs.readFileSync('academy.js','utf8').replace(/initializeAcademy\(\);\s*$/,''),context);
 vm.runInContext('render=()=>{};syncAcademy=async()=>{};',context);
 return {run:code=>vm.runInContext(code,context),tick:n=>{time+=n;},memory};
}
test('raw answers, elapsed time, skip and duplicate submit',()=>{const f=fixture();f.run("startSession([allContent()[0]],'typing');study.session.started=performance.now();study.session.answer='  我是学生  '");f.tick(2400);f.run('submitStudy();submitStudy()');assert.equal(f.run('historyData().attempts.length'),1);assert.equal(f.run('historyData().attempts[0].elapsed_ms'),2400);assert.equal(f.run('historyData().attempts[0].user_answer'),'  我是学生  ');assert.equal(f.run('historyData().attempts[0].is_correct'),true);f.run("startSession([allContent()[0]],'typing');submitStudy(true)");assert.equal(f.run('historyData().attempts[1].skipped'),true);assert.equal(f.run("historyData().reviews[contentKey(allContent()[0])].status"),'wrong');});
test('IME blocks submit and candidate Enter cooldown',()=>{const f=fixture();f.run("startSession([allContent()[0]],'typing');study.session.composing=true;study.session.answer='我是学生';submitStudy()");assert.equal(f.run('historyData().attempts.length'),0);f.run('study.session.composing=false;study.session.compositionEnded=performance.now();submitStudy()');assert.equal(f.run('historyData().attempts.length'),0);f.tick(100);f.run('submitStudy()');assert.equal(f.run('historyData().attempts.length'),1);});
test('guest/account histories remain isolated and guest import is idempotent',()=>{const f=fixture();f.run("startSession([allContent()[0]],'typing');submitStudy(true);currentUser={id:'a'}");assert.equal(f.run('historyData().attempts.length'),0);f.run('importGuestHistory();importGuestHistory()');assert.equal(f.run('historyData().attempts.length'),1);f.run("currentUser={id:'b'}");assert.equal(f.run('historyData().attempts.length'),0);f.run('currentUser=null');assert.equal(f.run('historyData().attempts.length'),1);});
test('category, favorites and wrong filters compose',()=>{const f=fixture();f.run("study.category='HSK1';study.starred=true;study.wrong=true;");assert.equal(f.run("selectedContent('sentence').length"),0);f.run("localStorage.setItem('academy.stars.guest',JSON.stringify({'academy-intro-1':true}));startSession([allContent()[0]],'typing');submitStudy(true)");assert.equal(f.run("selectedContent('sentence').length"),1);assert.equal(f.run("selectedContent('sentence')[0].id"),'academy-intro-1');});
test('old word pinyin grading stays compatible',()=>{const f=fixture();assert.equal(f.run("checkAnswer({hanzi:'你好',pinyin:'nǐ hǎo'},'ni hao')"),true);assert.equal(f.run("checkAnswer({hanzi:'你好',pinyin:'nǐ hǎo'},'你好')"),true);assert.equal(f.run("checkAnswer({hanzi:'你好',pinyin:'nǐ hǎo'},'你坏')"),false);});
test('legacy URLs map to new routes and unknown URLs stay unknown',()=>{const f=fixture();assert.equal(f.run("location.hash='#sentence';routeName()"),'typing');assert.equal(f.run("location.hash='#notes';routeName()"),'review');assert.equal(f.run("location.hash='#/missing';routeName()"),null);});
